name: dockerisedProcess
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python =3.6
  - pip
  - numpy =1.16.1
  - parallel =20190922
  - minimap2 =2.17
  - samtools =1.9
  - nanopolish =0.11.1
  - bcftools