name: dockerisedProcess
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - setuptools
  - quast =5.0.2
  - minimap2 =2.17
  - samtools =1.9
  - python =3.6
  - pip =19.2.3
  - pip:
    - seaborn==0.9.0
    - pandas==0.23.4
    - numpy==1.15.1
    - matplotlib