name: dockerisedProcess
channels:
  - bioconda
  - conda-forge
  - defaults
  - hcc
dependencies:
  - python =3.6
  - pip
  - numpy
  - minimap2 =2.17
  - samtools =1.9
  - scrappie
  - pomoxis==0.2.4